name: Multiplatform build and upload

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: false
        type: string

env:
  GH_TOKEN: ${{ secrets.GNUS_TOKEN_1 }}
jobs:
  build:
    runs-on: ${{matrix.host}}
    container:
      image: ${{matrix.container}}
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GNUS_TOKEN_1}}
    strategy:
      fail-fast: false
      matrix:
        target: [Android, iOS, OSX, Linux, Windows]
        build-type: [Debug, Release]
        abi: [""]
        include:
          - target: Linux
            host: ubuntu-22.04
            abi: x86_64
            build-type: Debug
          - target: Linux
            host: ubuntu-22.04
            abi: x86_64
            build-type: Release
          - target: Linux
            host: ubuntu-24.04-arm
            abi: aarch64
            build-type: Debug
            container: ghcr.io/geniusventures/debian-bullseye:latest
          - target: Linux
            host: ubuntu-24.04-arm
            abi: aarch64
            build-type: Release
            container: ghcr.io/geniusventures/debian-bullseye:latest
          - target: Windows
            host: windows-latest
          - target: OSX
            host: macos-latest
          - target: iOS
            host: macos-latest
          - target: Android
            host: ubuntu-22.04
            build-type: Release
            abi: arm64-v8a
          - target: Android
            host: ubuntu-22.04
            build-type: Release
            abi: armeabi-v7a
          - target: Android
            host: gv-Linux-large
            build-type: Debug
            abi: arm64-v8a
          - target: Android
            host: gv-Linux-large
            build-type: Debug
            abi: armeabi-v7a
        exclude:
          - target: Android
            abi: ""
          - target: Linux
            abi: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Configure Linux host
        if: ${{ runner.os == 'Linux'}}
        run: |
          sudo update-alternatives --install /usr/bin/cc cc $(which clang) 100
          sudo update-alternatives --install /usr/bin/c++ c++ $(which clang++) 100
          sudo update-alternatives --set cc $(which clang)
          sudo update-alternatives --set c++ $(which clang++)

          sudo apt install libvulkan-dev ninja-build -y
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Configure macOS host
        if: ${{ runner.os == 'macOS'}}
        run: |
          brew install ninja bash

          PATH="$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin:$PATH"
          echo "PATH=$PATH" >> $GITHUB_ENV

          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Add Darwin toolchain
        if: ${{ matrix.target == 'OSX'}}
        run: rustup target add x86_64-apple-darwin

      - name: Add iOS toolchain
        if: ${{ matrix.target == 'iOS' }}
        run: |
          rustup toolchain install nightly-aarch64-apple-darwin
          rustup component add rust-src --toolchain nightly-aarch64-apple-darwin
          rustup target add aarch64-apple-ios

      - name: Add Android toolchain
        if: ${{ matrix.target == 'Android' }}
        run: |
          NDK_VERSION="r27b"
          wget https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux.zip -O ndk.zip
          unzip ndk.zip -d $HOME

          echo "ANDROID_NDK_HOME=$HOME/android-ndk-$NDK_VERSION" >> $GITHUB_ENV

          rustup target add aarch64-linux-android
          rustup target add armv7-linux-androideabi

      - name: Install bindgen
        run: cargo install cbindgen

      - name: Add wasm Rust target
        run: rustup target add wasm32-unknown-emscripten

      - name: Set build directory
        run: |
          if [ '${{matrix.abi}}' ]; then
            BUILD_DIRECTORY=build/${{matrix.target}}/${{matrix.build-type}}/${{matrix.abi}}
          else
            BUILD_DIRECTORY=build/${{matrix.target}}/${{matrix.build-type}}
          fi
          echo "BUILD_DIRECTORY=$BUILD_DIRECTORY" >> $GITHUB_ENV
        shell: bash

      - name: Configure CMake for Mac
        if: ${{ matrix.target == 'OSX'}}
        run: cmake -S build/${{matrix.target}} -B $BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DPLATFORM=MAC_UNIVERSAL

      - name: Configure CMake for iOS
        if: ${{ matrix.target == 'iOS'}}
        run: cmake -S build/${{matrix.target}} -B $BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DPLATFORM=OS64

      - name: Configure CMake for Android
        if: ${{ matrix.target == 'Android'}}
        run: cmake -S build/${{matrix.target}} -B $BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DANDROID_ABI=${{matrix.abi}}

      - name: Configure CMake for Windows
        if: ${{ matrix.target == 'Windows' }}
        run: cmake -S build/${{matrix.target}} -B $env:BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

      - name: Configure CMake for Linux
        if: ${{ matrix.target == 'Linux' }}
        run: cmake -S build/${{matrix.target}} -B $BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

      - name: Build thirdparty
        working-directory: ${{env.BUILD_DIRECTORY}}
        run: cmake --build . --config ${{matrix.build-type}} -j

      - name: Compress directories
        if: github.ref_name == 'main' || github.ref_name == 'develop'
        working-directory: ${{env.BUILD_DIRECTORY}}
        shell: bash
        run: |
          if [ '${{matrix.abi}}' ]; then
            FILE_NAME="${{matrix.target}}-${{matrix.abi}}-${{matrix.build-type}}.tar.gz"
          else
            FILE_NAME="${{matrix.target}}-${{matrix.build-type}}.tar.gz"
          fi

          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV

          tar --no-wildcards-match-slash --exclude='./*/src' --exclude='./*/tmp' --transform='s|^\.|${{env.BUILD_DIRECTORY}}|g' -czf $FILE_NAME ./*/

      - name: Set release tag
        shell: bash
        run: |
          if ${{ github.event_name == 'workflow_dispatch' }} && [ '${{ github.event.inputs.tag }}' ]; then
              RELEASE_TAG="${{ github.event.inputs.tag }}"
              IS_TAG_RELEASE="true"
          else
              RELEASE_TAG="${{ matrix.target }}-${{ github.ref_name }}-${{ matrix.build-type }}"
              IS_TAG_RELEASE="false"
          fi

          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          echo "IS_TAG_RELEASE=$IS_TAG_RELEASE" >> $GITHUB_ENV

      - name: Wait for primary release creation
        if: (github.ref_name == 'main' || github.ref_name == 'develop') && matrix.abi != '' && !((matrix.target == 'Linux' && matrix.abi == 'x86_64') || (matrix.target == 'Android' && matrix.abi == 'arm64-v8a'))
        run: |
          ATTEMPT=1
          MAX_ATTEMPTS=720
          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
              if gh release view "$RELEASE_TAG" >/dev/null 2>&1; then
                  # Check if it's at the correct commit
                  if gh release view $RELEASE_TAG | grep -q "${{ github.sha }}"; then
                    echo "Release $RELEASE_TAG found!"
                    break
                  fi
              fi
              echo "Waiting for release $RELEASE_TAG (attempt $ATTEMPT/$MAX_ATTEMPTS)..."
              sleep 10
              ATTEMPT=$((ATTEMPT + 1))
          done

          if [ $ATTEMPT -gt $MAX_ATTEMPTS ]; then
              echo "Timed out waiting for release $RELEASE_TAG"
              exit 1
          fi
        shell: bash

      - name: Create release tag
        if: (github.ref_name == 'main' || github.ref_name == 'develop') && (matrix.abi == '' || (matrix.target == 'Linux' && matrix.abi == 'x86_64') || (matrix.target == 'Android' && matrix.abi == 'arm64-v8a'))
        id: create-release-tag
        run: |
          echo "Checking if release $RELEASE_TAG exists..."

          if gh release view "$RELEASE_TAG" >/dev/null 2>&1; then
              if [ "$IS_TAG_RELEASE" == "false" ]; then
                  echo "Deleting existing release/tag $RELEASE_TAG..."
                  gh release delete "$RELEASE_TAG" --yes || true
                  git push origin ":refs/tags/$RELEASE_TAG" || true
              fi
          fi

          echo "Creating new tag $RELEASE_TAG..."
          git tag "$RELEASE_TAG" "${{ github.sha }}"
          git push origin "$RELEASE_TAG"

          echo "Creating GitHub release $RELEASE_TAG..."
          gh release create "$RELEASE_TAG" \
          --target "${{ github.sha }}" \
          -t "${{ matrix.target }} ${{ github.ref_name }} ${{ matrix.build-type }} build" \
          -n "Branch: ${{ github.ref_name }} | SHA: ${{ github.sha }}" \
          $( [ "$IS_TAG_RELEASE" = "true" ] && echo "--latest" || echo "--prerelease" )
        shell: bash

      - name: Upload file
        if: github.ref_name == 'main' || github.ref_name == 'develop'
        working-directory: ${{env.BUILD_DIRECTORY}}
        run: gh release upload ${{env.RELEASE_TAG}} ${{env.FILE_NAME}} --clobber
