# This is a workflow to cache the sources for all the builds

name: Cache Source Files

# Controls when the workflow will run
# Triggers the workflow on push or pull request events and manually from the Actions tab
on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  setup:
      runs-on: ubuntu-latest
      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
      steps:
        - name: Cache main Source Files without .git
          uses: GeniusVentures/cache-multi@v3.2.2
          id: cache-source-directory
          with:
            path: |
              !.git/**
              ${{github.workspace}}/**
            key: third-${{ github.sha }}

        - name: Check out main third party without submodules
          if: steps.cache-source-directory.outputs.cache-hit != 'true'
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          uses: actions/checkout@v3
          with:
            path: '${{github.workspace}}'

        - name: Set matrix of submodules
          id: set-matrix
          run: |
            content=$(git submodule)
            jsonContent="{ \"include\": [  "
            first="true"
            while read longsha name; do
              longsha="${longsha/'-'/}"
              shortsha="${longsha:0:7}"
              if [[ "$first" != "true" ]]; then
                jsonContent+=","
              fi
              jsonContent+="{ \"name\": \"$name\", \"shortsha\": \"$shortsha\", \"longsha\": \"$slongsha\" }"
              first="false"
            done <<<"$content"
            jsonContent+="] }"
            echo "matrix=$jsonContent" >> $GITHUB_OUTPUT
          shell: bash
          working-directory: ${{github.workspace}}

  cache_src:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    if: false
    steps:
      - uses: GeniusVentures/cache-multi@v3.2.2
        id: cache-tp-source-directory
        with:
          path: |
            !.git/**
            ${{github.workspace}}/**
          key: third-${{ github.sha }}

      - if: steps.cache-tp-source-directory.outputs.cache-hit != 'true'
        run: |
          echo "Couldn't find cached thirdparty code, third-${{ github.sha }} fatal error!"
          exit 1

      - name: Cache Submodule Source Files without .git
        id: cache-source-directory
        uses: GeniusVentures/cache-multi@v3.2.2
        with:
          path: |
            !.git/**
            ${{github.workspace}}/${{ matrix.name }}/**
          key: ${{ matrix.name }}-${{ matrix.shortsha }}

      - name: Git clone submodule source code
        if: steps.cache-source-directory.outputs.cache-hit != 'true'
        run: |
          echo "Cloning source for ${{ matrix.name }}"
          git submodule update --init --recursive -- ${{ matrix.name }}
        shell: bash
        working-directory: ${{github.workspace}}

  build_targets:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: GeniusVentures/cache-multi@v3.2.2
        id: cache-tp-source-directory
        with:
          path: |
            !.git/**
            ${{github.workspace}}/**
          key: third-${{ github.sha }}

      - if: steps.cache-tp-source-directory.outputs.cache-hit != 'true'
        run: |
          echo "Couldn't find cached thirdparty code, third-${{ github.sha }} fatal error!"
          exit 1

      - name: Create Inputs for src caches to load
        id: cache-multi-parameters
        run: |
          # now reload the json content into variables list
          reloadcontent=$(echo '${{ needs.setup.outputs.matrix }}' | perl -pe "s/.*?(?:\{[ \t]*?\"name\":[ \t]*?\"(.+?)\".[ \t]*?\"shortsha\":[ \t]*?\"(.+?)\"(.*?)\}),*\]*[ \t]*\}*/\1 \2\n/g")
  
          keysJsonContent="\"keys\": [ "
          pathsJsonContent="\"paths\": [ "
          first="true"
          while read name shortsha; do
          if [[ "$first" != "true" ]]; then
          keysJsonContent+=","
            pathsJsonContent+=","
          fi
          keysJsonContent+="\"$name-$shortsha\""
          pathsJsonContent+="[ \"!.git/**\", \"$name/**\" ]"
          first="false"
          done <<<"$reloadcontent"
          fullJsonContent="{ $keysJsonContent ], $pathsJsonContent ] }"

          echo "CACHE_MULTI_PARAMETERS=$fullJsonContent"      
          echo "CACHE_MULTI_PARAMETERS=$fullJsonContent" >> $GITHUB_OUTPUT

      - name: Load the source Cache(s) into the system
        uses: GeniusVentures/cache-multi/restoremulti@v3.2.2
        with:
          #${{ fromJson(steps.cache-multi-parameters.outputs.CACHE_MULTI_PARAMETERS) }}
          keys:
            - Boost.DI-c5287ee
            - GSL-7e99e76
            - GTest-516940f
            - MoltenVK-c376273
            - Parabeac-Core-6d78541
            - Vulkan-Headers-1dace16
            - Vulkan-Loader-fbea18e
            - abseil-cpp-522606b
            - boost-32da69a
            - boost-for-mobile-9460203
            - build/Android/Boost-for-Android-4ade6ef
            - c-ares-2aa086f
            - celer-network/pb3-gen-sol-a533630
            - cpp-ipfs-http-client-763e59a
            - cryptopp-1c34979
            - curl-android-ios-da6f0d2
            - delta-enabled-crdts-f76171f
            - ed25519-ff7065e
            - flutter-8264cb3
            - fmt-7bdf062
            - gnostic-b262eed
            - grpc-0a82c02
            - hat-trie-343e0da
            - ipfs-bitswap-cpp-4230fef
            - ipfs-lite-cpp-ba8c735
            - ipfs-pubsub-35cdf9b
            - json-d70d06a
            - jsonrpc-lean-534a9cd
            - kompute-31db504
            - libp2p-ad2f4d0
            - libp2p-sqlite-modern-cpp-fc3b700
            - libsecp256k1-b59ea74
            - lmdb-b3c9088
            - openssl-31efcf2
            - rapidjson-f56928d
            - restclient-cpp-7d31d1e
            - rocksdb-24a3f36
            - soralog-3ebc084
            - spdlog-100f300
            - sr25519-donna-987e2c5
            - wallet-core-f50d771
            - xxhash-520f546
            - yaml-cpp-1b50109
          paths:
            - - "!.git/**"
              - Boost.DI/**
            - - "!.git/**"
              - GSL/**
            - - "!.git/**"
              - GTest/**
            - - "!.git/**"
              - MoltenVK/**
            - - "!.git/**"
              - Parabeac-Core/**
            - - "!.git/**"
              - Vulkan-Headers/**
            - - "!.git/**"
              - Vulkan-Loader/**
            - - "!.git/**"
              - abseil-cpp/**
            - - "!.git/**"
              - boost/**
            - - "!.git/**"
              - boost-for-mobile/**
            - - "!.git/**"
              - build/Android/Boost-for-Android/**
            - - "!.git/**"
              - c-ares/**
            - - "!.git/**"
              - celer-network/pb3-gen-sol/**
            - - "!.git/**"
              - cpp-ipfs-http-client/**
            - - "!.git/**"
              - cryptopp/**
            - - "!.git/**"
              - curl-android-ios/**
            - - "!.git/**"
              - delta-enabled-crdts/**
            - - "!.git/**"
              - ed25519/**
            - - "!.git/**"
              - flutter/**
            - - "!.git/**"
              - fmt/**
            - - "!.git/**"
              - gnostic/**
            - - "!.git/**"
              - grpc/**
            - - "!.git/**"
              - hat-trie/**
            - - "!.git/**"
              - ipfs-bitswap-cpp/**
            - - "!.git/**"
              - ipfs-lite-cpp/**
            - - "!.git/**"
              - ipfs-pubsub/**
            - - "!.git/**"
              - json/**
            - - "!.git/**"
              - jsonrpc-lean/**
            - - "!.git/**"
              - kompute/**
            - - "!.git/**"
              - libp2p/**
            - - "!.git/**"
              - libp2p-sqlite-modern-cpp/**
            - - "!.git/**"
              - libsecp256k1/**
            - - "!.git/**"
              - lmdb/**
            - - "!.git/**"
              - openssl/**
            - - "!.git/**"
              - rapidjson/**
            - - "!.git/**"
              - restclient-cpp/**
            - - "!.git/**"
              - rocksdb/**
            - - "!.git/**"
              - soralog/**
            - - "!.git/**"
              - spdlog/**
            - - "!.git/**"
              - sr25519-donna/**
            - - "!.git/**"
              - wallet-core/**
            - - "!.git/**"
              - xxhash/**
            - - "!.git/**"
              - yaml-cpp/**