# This is a workflow to cache the sources for all the builds

name: Cache Source Files

# Controls when the workflow will run
# Triggers the workflow on push or pull request events and manually from the Actions tab
on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  setup:
      runs-on: ubuntu-latest
      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
      steps:
        - name: Check out main third party without submodules
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          uses: actions/checkout@v3
          with:
            path: '${{github.workspace}}'
        - name: Set matrix of submodules
          id: set-matrix
          run: |
            content=`git submodule | sed -E 's/-*([^ ]+) (.*)/{ "name": "\2", "longsha": "\1" },/' | sed '$ s/,$//g'`
            content="${content//'%'/'%25'}"
            content="${content//$'\n'/}"
            content="${content//$'\r'/}"
            # end of optional handling for multi line json
            echo "matrix=\"{ \"include\": [ $content ] }\"" >> $GITHUB_OUTPUT
            echo "matrix=$content"
          working-directory: ${{github.workspace}}

  cache_or_load_src:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Echo information
        run: |
          echo "${matrix.name}, ${matrix.longsha}"
