# This is a workflow to cache the sources for all the builds

name: Cache Source Files

# Controls when the workflow will run
# Triggers the workflow on push or pull request events and manually from the Actions tab
on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  setup:
      runs-on: ubuntu-latest
      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
      steps:
        - name: Cache main Source Files without .git
          uses: actions/cache@v3
          id: cache-source-directory
          with:
            path: |
              !.git/**
              ${{github.workspace}}/**
            key: third-${{ github.sha }}

        - name: Check out main third party without submodules
          if: steps.cache-source-directory.outputs.cache-hit != 'true'
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          uses: actions/checkout@v3
          with:
            path: '${{github.workspace}}'

        - name: Set matrix of submodules
          id: set-matrix
          run: |
            content=$(git submodule)
            jsonContent="{ \"include\": [  "
            first="true"
            while read longsha name; do
              longsha="${longsha/'-'/}"
              shortsha="${longsha:0:7}"
              if [[ "$first" != "true" ]]; then
                jsonContent+=","
              fi
              jsonContent+="{ \"name\": \"$name\", \"shortsha\": \"$shortsha\", \"longsha\": \"$slongsha\" }"
              first="false"
            done <<<"$content"
            jsonContent+="] }"
            echo "matrix=$jsonContent" >> $GITHUB_OUTPUT
          shell: bash
          working-directory: ${{github.workspace}}

  cache_src:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/cache@v3
        id: cache-tp-source-directory
        with:
          path: |
            !.git/**
            ${{github.workspace}}/**
          key: third-${{ github.sha }}

      - if: steps.cache-tp-source-directory.outputs.cache-hit != 'true'
        run: |
          echo "Couldn't find cached thirdparty code, third-${{ github.sha }} fatal error!"
          exit 1

      - name: Cache Submodule Source Files without .git
        id: cache-source-directory
        uses: actions/cache@v3
        with:
          path: |
            !.git/**
            ${{github.workspace}}/${{ matrix.name }}/**
          key: ${{ matrix.name }}-${{ matrix.shortsha }}

      - name: Git clone submodule source code
        if: steps.cache-source-directory.outputs.cache-hit != 'true'
        run: |
          echo "Cloning source for ${{ matrix.name }}"
          git submodule update --init --recursive -- ${{ matrix.name }}
        shell: bash
        working-directory: ${{github.workspace}}

build_targets:
  needs: [setup, cache_src]
  runs-on: ubuntu-latest
#  matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
  steps:
    - uses: actions/cache-multi
      id: cache-tp-source-directory
      with:
        path: |
          !.git/**
          ${{github.workspace}}/**
        key: third-${{ github.sha }}

    - if: steps.cache-tp-source-directory.outputs.cache-hit != 'true'
      run: |
        echo "Couldn't find cached thirdparty code, third-${{ github.sha }} fatal error!"
        exit 1

    - name: Create Inputs for src caches to load
      id: cache-multi-parameters
      run: |
        # now reload the json content into variables list
        reloadcontent=$(echo "${{ needs.setup.outputs.matrix }}" | perl -pe "s/.*?(?:\{[ \t]*?\"name\":[ \t]*?\"(.+?)\".[ \t]*?\"shortsha\":[ \t]*?\"(.+?)\"(.*?)\}),*\]*[ \t]*\}*/\1 \2\n/g")

        keysJsonContent="\"keys\": [ "
        pathsJsonContent="\"paths\": [\n "
        first="true"
        while read name shortsha; do
        echo "====> $name, $shortsha"
        if [[ "$first" != "true" ]]; then
        keysJsonContent+=","
          pathsJsonContent+=","
        fi
        keysJsonContent+="\"$name-$shortsha\""
        pathsJsonContent+="[ \"!.git/**\", \"$name/**\" ]"
        first="false"
        done <<<"$reloadcontent"
        fullJsonContent="{ $keysJsonContent ], $pathsJsonContent ] }"
        
        echo "CACHE_MULTI_PARAMETERS=\"$fullJsonContent\"" >> $$GITHUB_OUTPUT

    - name: Load the source Cache(s) into the system
      uses: actions/cache-multi/restoremulti
      with:
        ${{ fromJson(steps.cache-multi-parameters.outputs.CACHE_MULTI_PARAMETERS) }}
