# This is a basic workflow to help you get started with Actions

name: Release Build CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3
  
  BuildAndTest:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/.build          

      - name: Configure CMake
        working-directory: ${{github.workspace}}/.build
        run: cmake -S ../build/Linux/ -DCMAKE_BUILD_TYPE=Release

      - name: Compile
        working-directory: ${{github.workspace}}/.build
        run: make -j8
      
