name: iOS Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
      - ".gitignore"
  pull_request:
  workflow_dispatch:

jobs:
  iOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      # Workaround for arm64 build
      - name: Ensure latest macOS SDK is used
        run: |
          sudo xcode-select --switch "$(find /Applications -mindepth 1 -maxdepth 1 ! -type l | grep "Xcode_*[\.0-9]*app" | sort -V | tail -1)/Contents/Developer"
          sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*

      - uses: actions/setup-python@v5
        with:
          python-version: "3.5.10"
          cache: "pip"

      - name: Install Rust dependencies
        run: |
          rustup target add x86_64-apple-ios aarch64-apple-ios-sim aarch64-apple-ios aarch64-apple-darwin x86_64-apple-darwin

      - name: Install bindgen
        run: cargo install cbindgen cargo-lipo

      - name: Configure CMake
        run: cmake -S build/iOS -B build/iOS/Release -DCMAKE_BUILD_TYPE=Release -DiOS_ABI=arm64-v8a -DIOS_ARCH="arm64" -DENABLE_ARC=0 -DENABLE_BITCODE=0 -DENABLE_VISIBILITY=1 -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_SYSTEM_PROCESSOR=arm64 -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/build/iOS/iOS.cmake

      - name: Build project
        run: cmake --build build/iOS/Release --config Release --parallel
