# This is a basic workflow to help you get started with Actions

name: Linux Build

# Controls when the workflow will run
# Triggers the workflow on push or pull request events and manually from the Actions tab
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'
      - '.gitignore'
  pull_request:
  workflow_dispatch:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 8

jobs:
  Linux:
      runs-on: ubuntu-latest
      env:
        MAKEFLAGS: "-j 8"
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
          with:
            submodules: 'recursive'

        - name: Create Build Directory
          run: cmake -E make_directory ${{github.workspace}}/.build

        - name: Configure CMake
          working-directory: ${{github.workspace}}/.build
          run: cmake -S ../build/Linux/ -DCMAKE_BUILD_TYPE=Release

        - name: Compile
          working-directory: ${{github.workspace}}/.build
          run: make
