name: Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set clang as the default compiler
        run: |
          sudo update-alternatives --install /usr/bin/cc cc $(which clang) 100
          sudo update-alternatives --install /usr/bin/c++ c++ $(which clang++) 100
          sudo update-alternatives --set cc $(which clang)
          sudo update-alternatives --set c++ $(which clang++)

      - name: Add Rust target
        run: rustup target add wasm32-unknown-emscripten

      - name: Install bindgen
        run: cargo install cbindgen

      - name: Install Ninja
        run: sudo apt install ninja-build -y

      - name: Configure CMake
        run: cmake -S build/Linux/ -B build/Linux/Release -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build project
        run: cmake --build build/Linux/Release --config Release -j
