# This is a basic workflow to help you get started with Actions

name: Linux Build

# Controls when the workflow will run
# Triggers the workflow on push or pull request events and manually from the Actions tab
on:
  workflow_dispatch:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 8

jobs:
  Linux:
      runs-on: ubuntu-latest
      env:
        MAKEFLAGS: "-j 8"
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
          with:
            submodules: 'recursive'

        - name: Install Rust dependencies
          run: |
            rustup update
            rustup toolchain install stable
            rustup default stable
            rustup target add x86_64-unknown-linux-gnu
            rustup target add wasm32-unknown-emscripten
            cargo install cbindgen

        - name: Create Build Directory
          run: |
            mkdir -p ${{github.workspace}}/Linux/build/Release/
            update-alternatives --set c++ /usr/bin/clang++
            update-alternatives --set cc /usr/bin/clang
            cd ${{github.workspace}}/Linux/build/Release/
            cmake .. -DCMAKE_BUILD_TYPE=Release
            make

