name: Mac OSX Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
      - ".gitignore"
  pull_request:
  workflow_dispatch:

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      # Workaround for arm64 build
      - name: Ensure latest macOS SDK is used
        run: |
          sudo xcode-select --switch "$(find /Applications -mindepth 1 -maxdepth 1 ! -type l | grep "Xcode_[\.0-9]*app" | sort -V | tail -1)/Contents/Developer"
          sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*

      - name: Install Rust dependencies
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          rustup target add wasm32-unknown-emscripten

      - name: Install bindgen
        run: cargo install cbindgen cargo-lipo

      - name: Configure CMake
        run: cmake -S build/OSX -B build/OSX/Release -DCMAKE_BUILD_TYPE=Release

      - name: Compile
        run: cmake --build build/OSX/Release --config Release --parallel
