name: Mac OSX Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
      - ".gitignore"
  pull_request:
  workflow_dispatch:

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Add Rust targets
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add wasm32-unknown-emscripten

      - name: Install bindgen
        run: cargo install cbindgen

      - name: Install ccache
        run: brew install ccache

      - name: Configure CMake
        run: cmake -S build/OSX -B build/OSX/Release -DCMAKE_BUILD_TYPE=Release

      - name: Compile
        run: cmake --build build/OSX/Release --config Release
