name: Multiplatform build

on:
  workflow_dispatch:

jobs:
  android-debug:
    uses: ./.github/workflows/build.yml
    with:
      target: Android
      build-type: Debug
      abi: arm64
  ios-debug:
    uses: ./.github/workflows/build.yml
    with:
      target: iOS
      build-type: Debug
  linux-debug:
    uses: ./.github/workflows/build.yml
    with:
      target: Linux
      build-type: Debug
  macos-debug:
    uses: ./.github/workflows/build.yml
    with:
      target: OSX
      build-type: Debug
  windows-debug:
    uses: ./.github/workflows/build.yml
    with:
      target: Windows
      build-type: Debug
  android-release:
    uses: ./.github/workflows/build.yml
    with:
      target: Android
      build-type: Release
      abi: arm64
  ios-release:
    uses: ./.github/workflows/build.yml
    with:
      target: iOS
      build-type: Release
  linux-release:
    uses: ./.github/workflows/build.yml
    with:
      target: Linux
      build-type: Release
  macos-release:
    uses: ./.github/workflows/build.yml
    with:
      target: OSX
      build-type: Release
  windows-release:
    uses: ./.github/workflows/build.yml
    with:
      target: Windows
      build-type: Release
