# This is a workflow to cache the sources for all the builds

name: test source caching and cleaning

# Controls when the workflow will run
# Triggers the workflow on push or pull request events and manually from the Actions tab
on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}
  MAKEFLAGS: "-j 8"
  CMAKE_BUILD_PARALLEL_LEVEL: 8

jobs:
  setup-src-cache:
    runs-on: ubuntu-latest
    outputs:
      THIRD_PARTY_CACHE_NAME_KEY: ${{ steps.tp-check.outputs.THIRD_PARTY_CACHE_NAME_KEY }}
      FOUND_THIRD_PARTY_CURRENT: ${{ steps.tp-check.outputs.FOUND_THIRD_PARTY_CURRENT }}
      CACHE_MATRIX: ${{ steps.set-cache-matrix.outputs.CACHE_MATRIX }}
      NEEDS_CACHE: ${{ steps.set-cache-matrix.outputs.NEEDS_CACHE }}
      CACHE_MULTI_PARAMETER_NAME_KEYS: ${{ steps.set-cache-matrix.outputs.CACHE_MULTI_PARAMETER_NAME_KEYS }}
      CACHE_MULTI_PARAMETER_PATHS: ${{ steps.set-cache-matrix.outputs.CACHE_MULTI_PARAMETER_PATHS }}
    steps:
      - name: Check out main third party without submodules
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
        with:
          path: .

      - name: Install gh cli extension actions-cache
        run: |
          type -p gh >/dev/null || {
            type -p curl >/dev/null || sudo apt install curl -y
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh -y
          }
          gh extension install actions/gh-actions-cache
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Find cache and Clean out old caches of thirdparty
        id: tp-check
        run: |
          echo "Fetching list of thirdparty cache keys to check if any old ones need deleting"
          cachesList=$(gh api -H "Accept: application/vnd.github+json" --paginate repos/GeniusVentures/thirdparty/actions/caches?key="thirdparty" | jq -r ".actions_caches[].key" | sort)
          longSHA="${{ github.sha }}"
          shortSHA="${longSHA:0:7}"
          tpCacheNameSHA="thirdparty-$shortSHA"
          
          notMatched="$(comm -3 --output-delimiter="" <(echo -en "$tpCacheNameSHA") <(echo -en "$cachesList"))"
          oldCaches="$(comm -13 --output-delimiter="" <(echo -en "$tpCacheNameSHA") <(echo -en "$notMatched"))"
          notCached="$(comm -12 --output-delimiter="" <(echo -en "$tpCacheNameSHA") <(echo -en "$notMatched"))"
          
          echo -e "notMatched: $notMatched"
          echo -e "oldCaches: $oldCaches"
          echo -e "notCached: $notCached"
          
          foundThirdPartyCurrent="true"
          if [[ $notCached == "$tpCacheNameSHA" ]]; then
            foundThirdPartyCurrent="false"
          fi
          
          #Set the field separator to new line
          IFS=$'\n'
          for oldCache in $oldCaches; do
            echo -e "Deleting old cache $oldCache"
            gh actions-cache delete $oldCache -R $REPO -B $BRANCH --confirm
          done
          
          echo "FOUND_THIRD_PARTY_CURRENT=$foundThirdPartyCurrent" >> $GITHUB_OUTPUT
          echo "THIRD_PARTY_CACHE_NAME_KEY=$tpCacheNameSHA" >> $GITHUB_OUTPUT
        shell: bash
        working-directory: ${{github.workspace}}

      - name: Cache main Source Files without .git, if not already cached
        if: ( steps.tp-check.outputs.FOUND_THIRD_PARTY_CURRENT == 'false' )
        uses: GeniusVentures/cache-multi@v3.2.3
        id: cache-source-directory
        with:
          key: ${{ steps.tp-check.outputs.THIRD_PARTY_CACHE_NAME_KEY }}
          path: |
            !.git/**
            ./**

      - name: Set matrix of src submodules that need updating
        id: set-cache-matrix
        run: |
          echo "Fetching list of cache keys to check if any old ones need deleting"
          cacheNames=""
          while read -r mode stage longsha location; do
            shortSHA="${longsha:0:7}"
            cacheNames+="s/$location-$shortSHA\n"
          done <<< $(git ls-tree HEAD | grep "160000 commit")

          cacheNames="$(echo -en "$cacheNames" | sort)"
          cachesList=$(gh api -H "Accept: application/vnd.github+json" --paginate repos/GeniusVentures/thirdparty/actions/caches?key="s/" | jq -r ".actions_caches[].key" | sort)

          notMatched="$(comm -3 --output-delimiter="" <(echo -en "$cacheNames") <(echo -en "$cachesList"))"
          oldCaches="$(comm -13 --output-delimiter="" <(echo -en "$cacheNames") <(echo -en "$notMatched"))"
          notCached="$(comm -12 --output-delimiter="" <(echo -en "$cacheNames") <(echo -en "$notMatched"))"

          # matrixJson = matrix of source code to cache, that isn't already cached
          matrixJson="[ "
          first=true
          # Set the field separator to new line
          IFS=$'\n'
          for toCache in $notCached; do
            len=${#toCache}
            startPos=$((len - 7))
            shortSHA="${toCache:$startPos:7}"
            # - 10 for s/ + '-' + shortSHA
            name="${toCache:2:$((len - 10))}"
            if [[ "$first" != "true" ]]; then
              matrixJson+=", "
            fi
            first=false
            matrixJson+="{ \"name\":  \"$name\", \"cache-name\": \"$toCache\" }"
          done
          matrixJson+=" ]"

          # delete old caches
          for oldCache in $oldCaches; do
            echo "Deleting old cache $oldCache"
            gh actions-cache delete $oldCache -R $REPO -B $BRANCH --confirm
          done

          echo "CACHE_MATRIX=$matrixJson" >> $GITHUB_OUTPUT
          if [[ "$notCached" != "" ]]; then
            echo "NEEDS_CACHE=true" >> $GITHUB_OUTPUT
          else
            echo "NEEDS_CACHE=false" >> $GITHUB_OUTPUT
          fi

          cacheNameKeysContent="[ "
          cachePathsContent="[ "
          first='true'
          for cacheName in $cacheNames; do
            len=${#cacheName}
            startPos=$((len - 7))
            shortSHA="${cacheName:$startPos:7}"
            # - 10 for s/ + '-' + shortSHA
            name="${cacheName:2:$((len - 10))}"
            if [[ "$first" != "true" ]]; then
              cacheNameKeysContent+=", "
              cachePathsContent+=", "
            fi
            first='false'
            cacheNameKeysContent+="\"$cacheName\""
            cachePathsContent+="[\"!./$name/.git/**\", \"./$name/**\"]"
          done

          cacheNameKeysContent+=" ]"
          echo "CACHE_MULTI_PARAMETER_NAME_KEYS=$cacheNameKeysContent" >> $GITHUB_OUTPUT

          cachePathsContent+=" ]"
          echo "CACHE_MULTI_PARAMETER_PATHS=$cachePathsContent" >> $GITHUB_OUTPUT

        shell: bash
        working-directory: ${{github.workspace}}

  cache-src:
    needs: setup-src-cache
    if: (needs.setup-src-cache.outputs.NEEDS_CACHE == 'true')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJson(needs.setup-src-cache.outputs.CACHE_MATRIX) }}
    steps:
      - name: Cache Third Party Directory
        uses: GeniusVentures/cache-multi/restore@v3.2.3
        id: cache-tp-source-directory
        with:
          key: ${{ needs.setup-src-cache.outputs.THIRD_PARTY_CACHE_NAME_KEY }}
          path: |
            !.git/**
            ./**

      - if: (steps.cache-tp-source-directory.outputs.cache-hit != 'true')
        run: |
          echo "Couldn't find cached thirdparty code, ${{ needs.setup-src-cache.outputs.THIRD_PARTY_CACHE_NAME_KEY }} fatal error!"
          exit 1

      - name: Git clone submodule source code
        run: |
          echo "Cloning source for ${{ matrix.name }}"
          git submodule update --init --recursive -- ${{ matrix.name }}
        shell: bash
        working-directory: ${{github.workspace}}

      - name: Cache Submodule Source Files without .git
        id: cache-source-directory
        uses: GeniusVentures/cache-multi@v3.2.3
        with:
          key: ${{ matrix.cache-name }}
          path: |
            !./${{ matrix.name }}/.git/**
            ./${{ matrix.name }}/**

  create-targets-matrix:
    needs: [ setup-src-cache, cache-src ]
    if: |
      always() &&
      needs.setup-src-cache.result == 'success' &&
      (needs.cache-src.result == 'success' || needs.cache-src.result == 'skipped')
    runs-on: ubuntu-latest
    outputs:
      TARGET_NAMES: ${{ steps.create-target-info.outputs.TARGET_NAMES }}
      TARGET_SHAS: ${{ steps.create-target-info.outputs.TARGET_SHAS }}
      TARGET_DIRECTORIES: ${{ steps.create-target-info.outputs.TARGET_DIRECTORIES }}
      TARGET_REPO_NAME: ${{ steps.create-target-info.outputs.TARGET_REPO_NAME }}
    steps:
      - name: Cache Third Party Directory
        uses: GeniusVentures/cache-multi/restore@v3.2.3
        id: cache-tp-source-directory
        with:
          key: ${{ needs.setup-src-cache.outputs.THIRD_PARTY_CACHE_NAME_KEY }}
          path: |
            !.git/**
            ./**

      - if: (steps.cache-tp-source-directory.outputs.cache-hit != 'true')
        run: |
          echo "Couldn't find cached thirdparty code, ${{ needs.setup-src-cache.outputs.THIRD_PARTY_CACHE_NAME_KEY }} fatal error!"
          exit 1

      - name: Cache Submodule Source Files without .git
        id: cache-source-directory
        uses: GeniusVentures/cache-multi/restoremulti@v3.2.3
        with:
          multi-key: ${{ needs.setup-src-cache.outputs.CACHE_MULTI_PARAMETER_NAME_KEYS }}
          path: ${{ needs.setup-src-cache.outputs.CACHE_MULTI_PARAMETER_PATHS }}

      - name: Create base target library names for target cache to create
        id: create-target-info
        run: |
          pushd build/Linux >/dev/null
          if [[ ! -d Release ]]; then
          mkdir Release
          fi
          
          cd Release
          if [[ ! -d CMakeFiles ]]; then
          cmake .. -DCMAKE_BUILD_TYPE=Release
          fi
          cd CMakeFiles
          cMakeNamesDirsAndRepoNames="$(grep -m2 -R --include "build.make" -e "make_directory.*thirdparty/[^/]*$" -e ".*-complete:.*-build" * |
          sed -E -n 's/^(.*)\.dir.*-complete: ([^/]*?)\/src.*/\1,\2,/p; s/.*thirdparty\/([^ ]*)$/\1|/p' |
            tr -d '\n' |
            tr '|' '\n')"
          popd >/dev/null
          
          # Initialize the variables
          cMakeNames=""
          buildDirectoryNames=""
          repoNames=""
          shortSHAs=""
          gitSubmodules="$(git ls-tree HEAD | grep "160000 commit")"
          
          while IFS=',' read -r cmakeName buildDir repoName; do
          
            # Append the fields to the appropriate array
            cMakeNames+="$cmakeName\n"
            buildDirectoryNames+="$buildDir\n"
            repoNames+="$repoName\n"
            longSHA="$(echo -e "$gitSubmodules" | grep -m1 "$repoName" | cut -d ' ' -f 3)"
            shortSHAs+="${longSHA:0:7}\n"
          
          done <<< "$cMakeNamesDirsAndRepoNames"
          
          echo "TARGET_NAMES=$cMakeNames" >>$GITHUB_OUTPUT
          echo "TARGET_SHAS=$shortSHAs" >>$GITHUB_OUTPUT
          echo "TARGET_DIRECTORIES=$buildDirectoryNames" >>$GITHUB_OUTPUT
          echo "TARGET_REPO_NAME=$repoNames" >>$GITHUB_OUTPUT

        shell: bash
        working-directory: ${{github.workspace}}

  build-targets-matrix:
    needs: [ setup-src-cache, cache-src, create-targets-matrix ]
    if: |
      always() &&
      needs.setup-src-cache.result == 'success' &&
      needs.create-targets-matrix.result == 'success' && 
      (needs.cache-src.result == 'success' || needs.cache-src.result == 'skipped')
    strategy:
      fail-fast: false
      matrix:
        build-type: [ Release, Debug ]
        target-build-data:
          - target-os: Linux
            runs-on: ubuntu-latest
            shell: bash
            setup-script: |
              echo "Setup for Linux Build"
#          - target-os: Android
#            runs-on: ubuntu-latest
#            shell: bash
#            setup-script: |
#              echo "Setup for Android Build"
#              git config --global core.autocrlf false
#              git config --global core.eol lf
#              echo "ANDROID_TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_ENV
#              echo "MAKEFLAGS=\"-j 8\"" >> $GITHUB_ENV
#              echo "ANDROID_NDK=$ANDROID_NDK_HOME" >> $GITHUB_ENV
#              echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
#            arch: |
#              arm64-v8a
#              x86_64
#              x86
#              armeabi-v7a
#          - target-os: OSX
#            runs-on: macos-latest
#            shell: bash
#            setup-script: |
#              echo "Setup for OSX Build"
#              find /Applications/Xcode* -maxdepth 0 -ls
#              sudo xcode-select --switch "$(find /Applications/Xcode*.app -maxdepth 0 | sort -V | tail -1)/Contents/Developer"
#              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
#            cmake-script: |
#              cd build/$TARGET_OS
#              mkdir Release
#              cd Release
#              cmake -S .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
#              echo "Compiling $TARGET_OS version $LIBRARY_VERSION of $LIBRARY_NAME"
#              make $LIBRARY_NAME
#          - target-os: iOS
#            runs-on: macos-latest
#            shell: bash
#            setup-script: |
#              echo "Setup for iOS Build"
#              find /Applications/Xcode* -maxdepth 0 -ls
#              sudo xcode-select --switch "$(find /Applications/Xcode*.app -maxdepth 0 | sort -V | tail -1)/Contents/Developer"
#              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
#            install-uses:
#              uses: actions/setup-python@v2
#              with:
#                python-version: '3.5'
#            cmake-script: |
#              cd build/$TARGET_OS
#              mkdir Release
#              cd Release
#              cmake -S .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DiOS_ABI=arm64-v8a -DIOS_ARCH="arm64" -DENABLE_ARC=0 -DENABLE_BITCODE=0 -DENABLE_VISIBILITY=1  -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_SYSTEM_PROCESSOR=arm64 -DCMAKE_TOOLCHAIN_FILE=$WORKSPACE/build/iOS/iOS.cmake
#              echo "Compiling $TARGET_OS version $LIBRARY_VERSION of $LIBRARY_NAME"
#              make $LIBRARY_NAME
#
#          - target-os: Windows
#            runs-on: windows-2022
#            setup-script: |
#              echo "Setup for Windows Build"
#            install-uses:
#              name: Configure build for Windows 10 x64
#              uses: ilammy/msvc-dev-cmd@v1
#              with:
#                arch: amd64
#                sdk: 10.0.22621.0
#                vsversion: 17

    runs-on: ${{ matrix.target-build-data.runs-on }}
    steps:
      - name: dumping matrix for each run
        run: |
          echo -e "matrix: ${{ toJson(matrix) }}"
          echo -e "cmakeNames: ${{ needs.create-targets-matrix.TARGET_NAMES }}"
          echo -e "targetSHAs: ${{ needs.create-targets-matrix.TARGET_SHAS }}"
          echo -e "buildDirs: ${{ needs.create-targets-matrix.TARGET_DIRECTORIES }}"
          echo -e "targetRepoName: ${{ needs.create-targets-matrix.TARGET_REPO_NAME }}"          

      - name: Install configuration
        uses: ChristopherHX/conditional@main
        with:
          if: ${{ matrix.target-build-data.install-uses != null }}
          step: |
            uses: ${{ matrix.target-build-data.install-uses.uses || '' }}
            with: ${{ (matrix.target-build-data.install-uses.with && toJSON(matrix.target-build-data.install-uses.with)) || '{}' }}

#      - name: Cache Third Party Directory
#        uses: GeniusVentures/cache-multi/restore@v3.2.2
#        id: cache-tp-source-directory
#        with:
#          key: ${{ needs.setup-src-cache.outputs.THIRD_PARTY_CACHE_NAME_KEY }}
#          path: |
#            !.git/**
#            ./**
#
#      - if: (steps.cache-tp-source-directory.outputs.cache-hit != 'true')
#        run: |
#          echo "Couldn't find cached thirdparty code, ${{ needs.setup-src-cache.outputs.THIRD_PARTY_CACHE_NAME_KEY }} fatal error!"
#          exit 1
#
#      - name: Cache Submodule Source Files without .git
#        id: cache-source-directory
#        uses: GeniusVentures/cache-multi@v3.2.2
#        with:
#          key: ${{ needs.setup-src-cache.outputs.CACHE_MULTI_PARAMETER_NAME_KEYS }}
#          path: ${{ needs.setup-src-cache.outputs.CACHE_MULTI_PARAMETER_PATHS }}
#
#
#      - name: Get libraries to build libraries
#        run: |
#          # build array of library names


