
name: test install functionality with if

# Controls when the workflow will run
# Triggers the workflow on push or pull request events and manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  build-targets-matrix-test:
    strategy:
      matrix:
        build-type: [ Release ]
        target-build-data:
          - target-os: OSX
            runs-on: macos-latest
            shell: bash
            setup-script: |
              echo "Setup for OSX Build"
              sudo xcode-select --switch "$(find /Applications/Xcode*.app -maxdepth 0 | sort -V | tail -1)/Contents/Developer"
              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
            cmake-script: |
              cd build/$TARGET_OS
              mkdir Release
              cd Release
              cmake -S .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
              echo "Compiling $TARGET_OS version $LIBRARY_VERSION of $LIBRARY_NAME"
              make $LIBRARY_NAME

          - target-os: Windows
            runs-on: windows-2022
            setup-script: |
              echo "Setup for Windows Build"
            install-uses:
              name: Configure build for Windows 10 x64
              uses: ilammy/msvc-dev-cmd@v1
              with:
                arch: amd64
                sdk: 10.0.22621.0
                vsversion: 17

    runs-on: ubuntu-latest
    steps:
      - name: Install configuration
        uses: ChristopherHX/conditional@main
        with:
          path: "testing"
          if: ${{ matrix.target-build-data.install-uses != null }}
          step: |
            uses: ${{ matrix.target-build-data.install-uses.uses || '' }}
            with: ${{ (matrix.target-build-data.install-uses.with && toJSON(matrix.target-build-data.install-uses.with)) || '{}' }}

