name: Windows Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
      - ".gitignore"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Configure Windows SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22000

      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Add rust target
        run: rustup target add wasm32-unknown-emscripten

      - name: Install bindgen
        run: cargo install cbindgen

      - name: Configure CMake
        uses: threeal/cmake-action@v1.3.0
        with:
          source-dir: build/Windows
          build-dir: build/Windows/Debug
          options: "CMAKE_BUILD_TYPE=Debug"

      - name: Build project
        run: cmake --build build/Windows/Debug --config Debug --parallel
