name: Windows Build

# Controls when the workflow will run
# Triggers the workflow on push or pull request events and manually from the Actions tab
on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
      - ".gitignore"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.5
        with:
          submodules: "recursive"

      - name: Configure Windows SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22000

      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: amd64

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "x86_64-pc-windows-msvc, wasm32-unknown-emscripten"

      - name: Install bindgen
        run: cargo install cbindgen

      - name: Run CMake
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          source-dir: build/Windows
          build-dir: build/Windows/Release
          options: "CMAKE_BUILD_TYPE=Release"
          build-args: "--config Release"
