# This is a basic workflow to help you get started with Actions

name: Windows Build

# Controls when the workflow will run
# Triggers the workflow on push or pull request events and manually from the Actions tab
on: [push, pull_request, workflow_dispatch]

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 8

jobs:
  Windows:
    runs-on: windows-2022
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
        with:
          sdk-version: 22000

      # Sets up the visual studio environment to build x64
      - name: Configure build for Windows 10 x64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/.build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/.build
        run: cmake -S ../build/Windows/ -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_VERSION="10.0"

      - name: Compile
        working-directory: ${{github.workspace}}/.build
        run: cmake --build . --config Release

