name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Add Rust target
        run: rustup target add wasm32-unknown-emscripten

      - name: Install ccache
        run: choco install ccache -y

      - name: Configure CMake
        run: cmake -S build/Windows -B build/Windows/Release -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build/Windows/Release --config Release -j
